use_ddp: False
port:

batch_size: 8

resume: # 가중치 경로 기입
force_resume: False
work_dir: ./result
max_iter: 800000
seed: 2
g_lr: 2e-4
d_lr: 1e-3
ac_lr: 2e-4
n_workers: 8
adam_betas: [0.0, 0.9]
init: kaiming

language: chn
decomposition:
primals:

dset_aug:
  normalize: True
  random_affine: False
  rotation_deg: [-180, 180]  # 원하는 각도 범위 (스칼라 값도 가능)
  rotation_p: 0.5  # 0이면 비활성

dset:
  train:
    data_dir:
  val:
    data_dir:
  test:
    data_dir:


# model
C: 32
g_args:
  style_enc:
    norm: in
    activ: relu
    pad_type: zero
    skip_scale_var: False
  experts:
    n_experts: 6
    norm: in
    activ: relu
    pad_type: zero
    skip_scale_var: False
  emb_num: 2
  dec:
    norm: in
    activ: relu
    pad_type: zero
    out: sigmoid
d_args:
  w_norm: spectral
  activ: relu
  gap_activ: relu
  pad_type: zero
  res_scale_var: False
ac_args:
  norm: in
  activ: relu
  pad_type: zero
  conv_dropout: 0.3
  clf_dropout: 0.2

# losses
pixel_loss_type: l1
pixel_w: 0.1
gan_w: 1.0
fm_layers: all
fm_w: 1.0
ac_w: 1.0
ac_gen_w: 1.0
ac_cross_w: 1.0
indp_exp_w: 1.0
indp_fact_w: 1.0

# etc
save: all-last
val_freq: 10000
save_freq: 50000
tb_freq: 100
img_freq: 10000

# threshold
threshold: 0.8
#epoch
epoch: 10000