use_ddp: False
port:

batch_size: 2

# style이랑 content 같은 가중치 쓸 때
resume: 
# 가중치style이랑 content따로 
split: True
resume_s: 
resume_c:

force_resume: False
work_dir: ./result
seed: 2
g_lr: 1e-8
style_lr: 2e-4
content_lr: 1e-5
n_workers: 8
adam_betas: [0.0, 0.9]
init: kaiming

dset_aug:
  normalize: True

dset:
  train:
    data_dir:
  val:
    data_dir:
  test:
    data_dir:


# model
C: 32
g_args:
  style_enc:
    norm: in
    activ: relu
    pad_type: zero
    skip_scale_var: False
  experts:
    n_experts: 6
    norm: in
    activ: relu
    pad_type: zero
    skip_scale_var: False
  emb_num: 2
  dec:
    norm: in
    activ: relu
    pad_type: zero
    out: sigmoid

# etc
val_freq: 1 # val 결과 기록 빈도
save_freq: 1 # weight 저장 빈도
img_freq: 1 # train 결과 기록 빈도

# threshold
threshold_s: 0.7
threshold_c: 0.9
#epoch
epoch: 500

#loss 계산시 style과 content반영 가중치
w_style: 1.0
w_content: 1.0